export const REPORTS: Record<string, string[]> = {
	user: [
		"Userbot, Autotyper, Scripting, Macro",
		"Spamming",
		"Mass Alternate Account Abuse",
		"Sharing exploits",
		"Abusing exploits",
		"Racism or other form of targeted hate",
		"Causing Drama/Witch hunting",
		"Using the bot for advertising",
		"Real Money Trading",
		"Discord ToS",
		"Other",
	],
	server: [
		"Server has userbots",
		"Rule breaking Giveaway Requirements or Bot Usage Requirements",
		"Server is trading invites/nitro for currency",
		"Server is knowingly breaking bot rules",
		"Server has alts",
		"Server is witch-hunting or causing drama around Dank Memer",
		"Other",
	],
};

export const APPEALS: Record<string, string[]> = {
	server: [
		"Discord's Terms of Service",
		"Dank Memer’s rules",
		"Pinging or DMing the Developers",
		"Causing or Perpetuating drama",
		"Using channels incorrectly",
		"Copypasta",
		"Spam",
		"Scamming",
		"Unsure",
	],
	user: [
		"Userbots, Scripting, or Macros",
		"Spamming",
		"Sharing or Using Exploits",
		"Alternate Account Abuse",
		"Racism, Homophobia, Sexism or Slurs",
		"Advertising",
		"Real Money Trading",
		"Drama/Witch Hunting",
		"Discord TOS and Guidelines",
		"Community Server Scamming",
		"Unsure",
	],
};
